### ISSUE TITLE
Creación de PDF "Base de datos del proyecto, sus diagramas y SQL.pdf"

### ISSUE THREAD

**Issue by carlosg14** [carlosg14/Proyecto-integrados#2]
PDF de presentaciones de google, debe tener:

- Primer pagina: Portada con titulo y participantes- Fecha
- Segunda pagina: DER
- Tercera pagina: Diagrama Crow Foot
- Paginas siguientes: 
                                *Tablas con los datos cargados
                                *3 paginas del SQL referido a: Insertar, Actualizar y Eliminar datos
                                *Consultas de: descripcion, sintaxis sql y tabla resultante:
                                     ○ La descripción de que hace la consulta
                                     ○ La consulta SQL correspondiente
                                     ○ La tabla resultante (si la tabla es muy grande, dejar una parte y aclarar cuántos son los registros que tiene 
                                         como resultado la consulta)
- Las consultas las deben sobre la Base de datos del proyecto:
                                ○ Una sola tabla (mostrando todos los datos),
                                ○ Una sola tabla (mostrando algunas columnas),
                                ○ Una sola tabla con where
                                ○ Una sola tabla con where utilizando between
                                ○ Una sola tabla con where utilizando limit
                                ○ Más de 1 tabla con inner join
                                ○ Más de 1 tabla con inner join y con filtros
                                ○ Opcionales:
                                                      ■ Una sola tabla con where con operador lógico
                                                      ■ Una sola tabla con where con operador de comparación
                                                      ■ Una sola tabla con group by
                                                      ■ Una sola tabla con group by usando alguna función agregada
                                                      ■ Más de 1 tabla sin join (solo from)

**Comment by morenoraul** [comment]
Se cambia de estado el issue a realizado
